---

- name: Check etcd PKI directory already exists
  stat: path={{ etcd_pki_dir }}
  register: check_etcd_pki_dir

- name: Create etcd PKI certificate directory
  when: not check_etcd_pki_dir.stat.exists
  file: path={{ etcd_pki_dir }} state=directory
  register: create_etcd_pki_dir

- name: Check etcd cert files
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ etcd_ca }}"
    - "{{ etcd_ca_key }}"
    - "{{ etcd_cert }}"
    - "{{ etcd_cert_key }}"
  register: check_etcd_cert_files

- name: Read etcd cert files
  when: item.stat.exists
  slurp: src={{ item.item }}
  with_items: "{{ check_etcd_cert_files['results'] }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: read_etcd_cert_files

- name: Write the content of etcd certs
  when: item[0].item == item[1].source and not item[0].stat.exists
  copy:
    mode: 0644
    content: "{{ item[1].content | b64decode  }}"
    dest: "{{ item[1].source }}"
  with_nested:
    - "{{ check_etcd_cert_files['results'] }}"
    - "{{ read_etcd_cert_files['results'] }}"
