---

- name: Include vars of cert-path.yml
  include_vars:
    file: defaults/cert-path.yml

- name: Check SSL CA json config
  stat: path={{ ca_config }}
  register: check_ca_config

- name: Generate SSL CA config
  when: not check_ca_config.stat.exists
  template: src=ca-config.json.j2 dest="{{ ca_config }}"
  register: gen_ca_config

- include_tasks: k8s-certs.yml

- include_tasks: k8s-kubelet-certs.yml

- include_tasks: etcd-certs.yml

- include_tasks: purge-files.yml
